FROM golang:1.25 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-s -w' -o /tmux-server ./cmd/tmux-server

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /tmux-server /tmux-server

EXPOSE 8080

ENTRYPOINT ["/tmux-server"]
