apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: android-release
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/v*]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo-url
        type: string
      - name: revision
        type: string
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskSpec:
          params:
            - name: repo-url
              type: string
            - name: revision
              type: string
          workspaces:
            - name: output
          steps:
            - name: clone
              image: alpine/git:latest
              workingDir: $(workspaces.output.path)
              script: |
                #!/bin/sh
                set -e
                git clone $(params.repo-url) .
                git checkout $(params.revision)
        params:
          - name: repo-url
            value: $(params.repo-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: source

      - name: resolve-version
        runAfter: [fetch-repository]
        taskSpec:
          params:
            - name: revision
              type: string
          results:
            - name: version
              description: The version tag (e.g. v1.0.0)
            - name: version-name
              description: The version without v prefix (e.g. 1.0.0)
            - name: version-code
              description: Numeric version code derived from version
          workspaces:
            - name: source
          steps:
            - name: resolve
              image: alpine/git:latest
              workingDir: $(workspaces.source.path)
              script: |
                #!/bin/sh
                set -e
                # Get the tag name pointing at this commit
                TAG=$(git describe --tags --exact-match $(params.revision) 2>/dev/null || echo "")
                if [ -z "$TAG" ]; then
                  echo "No tag found at revision $(params.revision)"
                  exit 1
                fi
                echo "Found tag: $TAG"
                echo -n "$TAG" > $(results.version.path)

                # Strip leading 'v' for version name
                VERSION_NAME=$(echo "$TAG" | sed 's/^v//')
                echo -n "$VERSION_NAME" > $(results.version-name.path)

                # Generate a numeric version code from semver (major*10000 + minor*100 + patch)
                MAJOR=$(echo "$VERSION_NAME" | cut -d. -f1)
                MINOR=$(echo "$VERSION_NAME" | cut -d. -f2)
                PATCH=$(echo "$VERSION_NAME" | cut -d. -f3)
                MAJOR=${MAJOR:-0}
                MINOR=${MINOR:-0}
                PATCH=${PATCH:-0}
                VERSION_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))
                echo -n "$VERSION_CODE" > $(results.version-code.path)
                echo "Version: $TAG, Name: $VERSION_NAME, Code: $VERSION_CODE"
        params:
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: source
            workspace: source

      - name: build-signed-apk
        runAfter: [resolve-version]
        taskSpec:
          params:
            - name: version-name
              type: string
            - name: version-code
              type: string
          workspaces:
            - name: source
          volumes:
            - name: keystore
              secret:
                secretName: android-keystore
          steps:
            - name: fix-permissions
              image: alpine:latest
              workingDir: $(workspaces.source.path)
              script: |
                #!/bin/sh
                set -e
                chmod -R 777 .
            - name: build
              image: cimg/android:2025.10.1
              workingDir: $(workspaces.source.path)/android
              env:
                - name: ANDROID_HOME
                  value: /home/circleci/android-sdk
                - name: GRADLE_USER_HOME
                  value: $(workspaces.source.path)/.gradle
              volumeMounts:
                - name: keystore
                  mountPath: /etc/android-keystore
              script: |
                #!/bin/sh
                set -e
                STORE_PASSWORD=$(cat /etc/android-keystore/keystore-password)
                KEY_ALIAS=$(cat /etc/android-keystore/key-alias)
                KEY_PASSWORD=$(cat /etc/android-keystore/key-password)

                sh ./gradlew assembleRelease --no-daemon --stacktrace \
                  -Prelease.keystorePath=/etc/android-keystore/keystore.jks \
                  -Prelease.storePassword="$STORE_PASSWORD" \
                  -Prelease.keyAlias="$KEY_ALIAS" \
                  -Prelease.keyPassword="$KEY_PASSWORD" \
                  -Papp.versionName="$(params.version-name)" \
                  -Papp.versionCode="$(params.version-code)"

                # Copy APK to a predictable location
                cp app/build/outputs/apk/release/app-release.apk \
                  $(workspaces.source.path)/tmux-viewer-$(params.version-name).apk
                echo "Signed APK built: tmux-viewer-$(params.version-name).apk"
        params:
          - name: version-name
            value: $(tasks.resolve-version.results.version-name)
          - name: version-code
            value: $(tasks.resolve-version.results.version-code)
        workspaces:
          - name: source
            workspace: source

      - name: create-release
        runAfter: [build-signed-apk]
        taskSpec:
          params:
            - name: version
              type: string
            - name: version-name
              type: string
          workspaces:
            - name: source
          volumes:
            - name: git-auth
              secret:
                secretName: "{{ git_auth_secret }}"
          results:
            - name: release-id
              description: The Gitea release ID
          steps:
            - name: release
              image: curlimages/curl:latest
              workingDir: $(workspaces.source.path)
              volumeMounts:
                - name: git-auth
                  mountPath: /etc/git-auth
              script: |
                #!/bin/sh
                set -e
                TOKEN=$(cat /etc/git-auth/git-provider-token)

                # Create the release
                HTTP_CODE=$(curl -w "%{http_code}" -sS -o /tmp/release-response.json -X POST \
                  "https://git.holdenitdown.net/api/v1/repos/{{ repo_owner }}/{{ repo_name }}/releases" \
                  -H "Authorization: token $TOKEN" \
                  -H "Content-Type: application/json" \
                  -d "{
                    \"tag_name\": \"$(params.version)\",
                    \"name\": \"tmux-viewer $(params.version)\",
                    \"body\": \"Android release $(params.version)\n\nInstall via [Obtainium](https://github.com/ImranR98/obtainium) using source URL \`https://git.holdenitdown.net/rfhold/dot\` with Forgejo (Codeberg) override.\",
                    \"draft\": false,
                    \"prerelease\": false
                  }")

                if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
                  echo "Failed to create release (HTTP $HTTP_CODE)"
                  cat /tmp/release-response.json
                  exit 1
                fi

                # Extract release ID
                RELEASE_ID=$(cat /tmp/release-response.json | sed -n 's/.*"id":\([0-9]*\).*/\1/p' | head -1)
                echo "Release created with ID: $RELEASE_ID (HTTP $HTTP_CODE)"
                echo -n "$RELEASE_ID" > $(results.release-id.path)
        params:
          - name: version
            value: $(tasks.resolve-version.results.version)
          - name: version-name
            value: $(tasks.resolve-version.results.version-name)
        workspaces:
          - name: source
            workspace: source

      - name: attach-apk
        runAfter: [create-release]
        taskSpec:
          params:
            - name: release-id
              type: string
            - name: version-name
              type: string
          workspaces:
            - name: source
          volumes:
            - name: git-auth
              secret:
                secretName: "{{ git_auth_secret }}"
          steps:
            - name: upload
              image: curlimages/curl:latest
              workingDir: $(workspaces.source.path)
              volumeMounts:
                - name: git-auth
                  mountPath: /etc/git-auth
              script: |
                #!/bin/sh
                set -e
                TOKEN=$(cat /etc/git-auth/git-provider-token)
                APK_FILE="tmux-viewer-$(params.version-name).apk"

                if [ ! -f "$APK_FILE" ]; then
                  echo "APK file not found: $APK_FILE"
                  ls -la *.apk 2>/dev/null || echo "No APK files in workspace"
                  exit 1
                fi

                echo "Uploading $APK_FILE to release $(params.release-id)..."
                HTTP_CODE=$(curl -w "%{http_code}" -sS -o /tmp/upload-response.json -X POST \
                  "https://git.holdenitdown.net/api/v1/repos/{{ repo_owner }}/{{ repo_name }}/releases/$(params.release-id)/assets?name=$APK_FILE" \
                  -H "Authorization: token $TOKEN" \
                  -F "attachment=@$APK_FILE")

                if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
                  echo "Failed to upload APK (HTTP $HTTP_CODE)"
                  cat /tmp/upload-response.json
                  exit 1
                fi
                echo "APK uploaded successfully (HTTP $HTTP_CODE)"
        params:
          - name: release-id
            value: $(tasks.create-release.results.release-id)
          - name: version-name
            value: $(tasks.resolve-version.results.version-name)
        workspaces:
          - name: source
            workspace: source

    finally:
      - name: notify-failure
        when:
          - input: $(tasks.status)
            operator: in
            values: ["Failed"]
        taskSpec:
          params:
            - name: version
              type: string
          volumes:
            - name: git-auth
              secret:
                secretName: "{{ git_auth_secret }}"
          steps:
            - name: comment
              image: curlimages/curl:latest
              volumeMounts:
                - name: git-auth
                  mountPath: /etc/git-auth
              script: |
                #!/bin/sh
                set -e
                TOKEN=$(cat /etc/git-auth/git-provider-token)
                HTTP_CODE=$(curl -w "%{http_code}" -sS -o /tmp/response.json -X POST \
                  "https://git.holdenitdown.net/api/v1/repos/{{ repo_owner }}/{{ repo_name }}/issues" \
                  -H "Authorization: token $TOKEN" \
                  -H "Content-Type: application/json" \
                  -d "{\"title\": \"Android release build failed for $(params.version)\", \"body\": \"The Android release pipeline failed. Check the [Tekton dashboard](https://tekton.holdenitdown.net) for details.\"}")
                if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
                  echo "Failed to create issue (HTTP $HTTP_CODE)"
                  cat /tmp/response.json
                  exit 1
                fi
                echo "Failure issue created (HTTP $HTTP_CODE)"
        params:
          - name: version
            value: "$(params.revision)"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi
